mncs:
  - Google
  - Microsoft
  - Amazon
  - Meta
  - Apple
  - Adobe
  - Oracle
  - Salesforce
  - SAP
  - IBM
  - Cisco
  - Intel
  - NVIDIA
  - Atlassian
  - Stripe
  - Shopify
  - Uber
  - Airbnb
  - Netflix
  - Goldman Sachs
  - JP Morgan
  - Morgan Stanley
  - Walmart
  - PayPal
  - Tata Consultancy Services
  - Infosys
  - Wipro
  - Cognizant
  - Accenture
  - Capgemini
